#!/bin/bash

# Wait for monitors to be detected (max 10 seconds)                                                                                                   │
# This prevents empty configuration if hyprctl isn't ready immediately                                                                                │
sleep 0.5
for i in {1..20}; do
    if hyprctl monitors | grep -q "Monitor"; then
        break
    fi
    sleep 0.5
done

# Initialize with defaults to avoid empty configuration
PRIMARY="preferred"
SECONDARY="preferred"

if hyprctl monitors | grep -qi "Japannext"; then
    PRIMARY="\$monitor_japannext"
elif hyprctl monitors | grep -qi "Xiaomi"; then
    PRIMARY="\$monitor_xiaomi"
elif hyprctl monitors | grep -qi "LG ULTRAGEAR"; then
    PRIMARY="\$monitor_lg"
fi

if hyprctl monitors | grep -qi "HDR WFHD"; then
    SECONDARY="\$monitor_wfhd"
elif hyprctl monitors | grep -qi "BenQ"; then
    SECONDARY="\$monitor_benq"
elif hyprctl monitors | grep -qi "LG ULTRAGEAR" && [[ "$PRIMARY" != "\$monitor_lg" ]]; then
    # Fallback for old setup: LG was secondary when Japannext/Xiaomi was primary
    SECONDARY="\$monitor_lg"
fi

# Write Hyprland config variables to a file
cat >~/.config/hypr/monitor-vars.conf <<EOF
# Auto-generated by set-monitor.sh
\$primary_monitor = $PRIMARY
\$secondary_monitor = $SECONDARY
EOF
