#!/bin/bash

if hyprctl monitors | grep -q "Japannext"; then
    PRIMARY="\$monitor_japannext"
elif hyprctl monitors | grep -q "Xiaomi"; then
    PRIMARY="\$monitor_xiaomi"
fi

if hyprctl monitors | grep -q "LG ULTRAGEAR"; then
    SECONDARY="\$monitor_lg"
elif hyprctl monitors | grep -q "BenQ"; then
    SECONDARY="\$monitor_benq"
fi

# Write Hyprland config variables to a file
cat > ~/.config/hypr/monitor-vars.conf <<EOF
# Auto-generated by set-monitor.sh
\$primary_monitor = $PRIMARY
\$secondary_monitor = $SECONDARY
EOF

