#!/bin/bash

# Wait for monitors to be detected (max 10 seconds)                                                                                                   │
# This prevents empty configuration if hyprctl isn't ready immediately                                                                                │
sleep 0.5
for i in {1..20}; do
    if hyprctl monitors | grep -q "Monitor"; then
        break
    fi
    sleep 0.5
done

# Initialize with defaults to avoid an unusable configuration.
PRIMARY="preferred"
SECONDARY="preferred"

MONITOR_JAPANNEXT="desc:MNT JAPANNEXT MNT"
MONITOR_LG="desc:LG Electronics LG ULTRAGEAR"
MONITOR_WFHD="desc:LG Electronics LG HDR WFHD"
MONITOR_BENQ="desc:BNQ BenQ EW3270U JCJ01494019"
MONITOR_XIAOMI="desc:Xiaomi Corporation Mi Monitor"

if hyprctl monitors | grep -qi "Japannext"; then
    PRIMARY="$MONITOR_JAPANNEXT"
elif hyprctl monitors | grep -qi "Xiaomi"; then
    PRIMARY="$MONITOR_XIAOMI"
elif hyprctl monitors | grep -qi "LG ULTRAGEAR"; then
    PRIMARY="$MONITOR_LG"
fi

if hyprctl monitors | grep -qi "HDR WFHD"; then
    SECONDARY="$MONITOR_WFHD"
elif hyprctl monitors | grep -qi "BenQ"; then
    SECONDARY="$MONITOR_BENQ"
elif hyprctl monitors | grep -qi "LG ULTRAGEAR" && [[ "$PRIMARY" != "$MONITOR_LG" ]]; then
    # Fallback for old setup: LG was secondary when Japannext/Xiaomi was primary
    SECONDARY="$MONITOR_LG"
fi

# Write variables consumed by the migrated Lua monitor configuration.
cat >~/.config/hypr/monitor-vars.lua <<EOF
-- Auto-generated by set-monitor.sh. Do not edit.
return {
  primary_monitor = "$PRIMARY",
  secondary_monitor = "$SECONDARY",
}
EOF

# The initial configuration load happens before this script runs. Reload once
# so the workspace rules use the newly detected monitors.
hyprctl reload
