# Application bindings
$terminal = uwsm app -- $TERMINAL
$browser = omarchy-launch-browser

bindd = SUPER SHIFT, T, Terminal, exec, $terminal --working-directory="$(omarchy-cmd-terminal-cwd)"
bindd = SUPER SHIFT, F, File manager, exec, uwsm app -- nautilus --new-window
bindd = SUPER SHIFT, B, Browser, exec, $browser
bindd = SUPER SHIFT ALT, B, Browser (private), exec, $browser --private
bindd = SUPER SHIFT, M, Music, exec, omarchy-launch-or-focus spotify
bindd = SUPER CTRL, T, Activity, exec, omarchy-launch-tui btop

bindd = SUPER SHIFT, D, Docker, exec, omarchy-launch-tui lazydocker
# bindd = SUPER SHIFT, G, Signal, exec, /home/albibenni/.local/share/bin/omarchy-launch-or-focus signal "uwsm app -- signal-desktop"
bindd = SUPER SHIFT, O, Obsidian, exec, omarchy-launch-or-focus obsidian "uwsm app -- obsidian -disable-gpu --enable-wayland-ime"
bindd = SUPER SHIFT, slash, Passwords, exec, uwsm app -- localsend

# If your web app url contains #, type it as ## to prevent hyperland treat it as comments
bindd = SUPER CTRL, C, Claude, exec, omarchy-launch-webapp "https://claude.ai"
bindd = SUPER CTRL, G, Gemini, exec, omarchy-launch-webapp "https://gemini.google.com/app"
bindd = SUPER SHIFT, C, Calendar, exec, omarchy-launch-webapp "https://calendar.google.com/"
bindd = SUPER SHIFT, Y, YouTube, exec, omarchy-launch-or-focus-webapp YouTube "https://youtube.com/"

# Lock system
bindd = SUPER CTRL SHIFT, L, Lock system, exec, omarchy-system-lock

# Monitor bindings
bindd = SUPER CTRL SHIFT, T, Toggle build-in display, exec, omarchy-hyprland-monitor-internal
# Overwrite existing bindings, like putting Omarchy Menu on Super + Space
# bindd = SUPER, D, Menu, exec, omarchy-launch-walker
# $terminal = uwsm app -- $TERMINAL

# bindd = SUPER CTRL, SPACE, Next background in theme, exec, omarchy-theme-bg-next
# bindd = SUPER SHIFT CTRL, SPACE, Theme menu, exec, omarchy-launch-walker -m menus:bennithemes --width 800 --minheight 400

# unbind = SUPER SHIFT, SPACE            # Toggle top bar (omarchy-toggle-waybar)
# unbind = SUPER CTRL, SPACE             # Next background in theme
# unbind = SUPER SHIFT CTRL, SPACE       # Theme menu
# unbind = SUPER, BACKSPACE              # Toggle window transparency
# unbind = SUPER SHIFT, BACKSPACE        # Toggle workspace gaps

