-- Port of bindings/bindings.conf: applications and web apps used previously.
-- Launch Ghostty directly to avoid Omarchy's xdg-terminal-exec wrapper.
o.bind("SUPER + SHIFT + T", "Terminal", { launch = "ghostty --gtk-single-instance=true" })
o.bind("SUPER + SHIFT + F", "File manager", { omarchy = "nautilus" })
o.bind("SUPER + SHIFT + B", "Browser", { omarchy = "browser" })
o.bind("SUPER + SHIFT + ALT + B", "Browser (private)", { omarchy = "browser --private" })
o.bind("SUPER + SHIFT + M", "Music", { omarchy = "spotify" })
o.bind("SUPER + CTRL + T", "Activity", { tui = "btop" })
o.bind("SUPER + SHIFT + D", "Docker", { tui = "lazydocker" })
o.bind("SUPER + SHIFT + O", "Obsidian", { launch = "obsidian", focus = "^obsidian$" })
o.bind("SUPER + SHIFT + SLASH", "LocalSend", { launch = "localsend", focus = "localsend" })
o.bind("SUPER + CTRL + C", "Claude", { webapp = "https://claude.ai" })
o.bind("SUPER + CTRL + G", "Gemini", { webapp = "https://gemini.google.com/app" })
o.bind("SUPER + SHIFT + C", "Calendar", { webapp = "https://calendar.google.com/" })
o.bind("SUPER + SHIFT + Y", "YouTube", { webapp = "https://youtube.com/", focus = true })
o.bind("SUPER + CTRL + SHIFT + K", "Lock system", "omarchy-system-lock")
o.bind("SUPER + CTRL + SHIFT + T", "Toggle built-in display", "omarchy-hyprland-monitor-internal")
